function randomDate() {
  const end = new Date();
  const start = new Date(2012, 0, 1);
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  );
}

const getRandomType = () => {
  const arr = [0, 1];
  const random = Math.floor(Math.random() * arr.length);
  return arr[random];
};

const data = [
  {
    id: "0444321160",
    name: "IXYS Corporation",
    note: "Translum cor atherectomy",
    amount: 19,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "2484893264",
    name: "Inphi Corporation",
    note: "Limb length-metacar/car",
    amount: 60,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4990348273",
    name: "FibroGen, Inc",
    note: "Bronchial operation NEC",
    amount: 28,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0938960164",
    name: "Beneficial Bancorp, Inc.",
    note: "Coronary arteriogram NEC",
    amount: 53,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7888771343",
    name: "ONEOK, Inc.",
    note: "Collaterl lig repair NEC",
    amount: 88,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7518295881",
    name: "iShares MSCI China ETF",
    note: "Manual exam of breast",
    amount: 78,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "2076468994",
    name: "Energizer Holdings, Inc.",
    note: "Excis knee semilun cartl",
    amount: 25,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3278562585",
    name: "John B. Sanfilippo & Son, Inc.",
    note: "Retinal tear laser coag",
    amount: 31,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5293698001",
    name: "Keane Group, Inc.",
    note: "Excision thyroid lesion",
    amount: 68,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "2774648599",
    name: "Willis Towers Watson Public Limited Company",
    note: "Open red-sep epiphy NEC",
    amount: 49,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7430470742",
    name: "Great Lakes Dredge & Dock Corporation",
    note: "Clos pharynx fistula NEC",
    amount: 8,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7187825358",
    name: "Cathay General Bancorp",
    note: "Detach retina laser coag",
    amount: 96,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4905558433",
    name: "Natural Alternatives International, Inc.",
    note: "Hand fasciectomy NEC",
    amount: 81,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "2798673054",
    name: "Heico Corporation",
    note: "Isotope inject/instill",
    amount: 18,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3100604296",
    name: "AG Mortgage Investment Trust, Inc.",
    note: "Bartholin gland marsup",
    amount: 54,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0951403885",
    name: "Karyopharm Therapeutics Inc.",
    note: "Toxicology-lower resp",
    amount: 15,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4435189895",
    name: "Westlake Chemical Corporation",
    note: "Facial bone repair NEC",
    amount: 51,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9151684551",
    name: "Hardinge Inc.",
    note: "Left heart cardiac cath",
    amount: 2,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3909776302",
    name: "Nuveen AMT-Free Municipal Credit Income Fund",
    note: "Clos endoscopic lung bx",
    amount: 41,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1587712296",
    name: "ASML Holding N.V.",
    note: "Destruct joint les NEC",
    amount: 39,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3518409921",
    name: "Heritage Insurance Holdings, Inc.",
    note: "Perc mtrl vlv repr w imp",
    amount: 53,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0220256268",
    name: "Box, Inc.",
    note: "Consultation NEC",
    amount: 80,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5813332081",
    name: "U.S. Bancorp",
    note: "Inject insulin",
    amount: 41,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7896578522",
    name: "First Trust Latin America AlphaDEX Fund",
    note: "Contrast bronchogram NEC",
    amount: 39,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6436276734",
    name: "Latin American Discovery Fund, Inc. (The)",
    note: "Lap dir ing hern-graft",
    amount: 79,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1081065664",
    name: "Akebia Therapeutics, Inc.",
    note: "Refus oth cervcl ant/ant",
    amount: 79,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1502886057",
    name: "FLIR Systems, Inc.",
    note: "Subtotal mastectomy",
    amount: 47,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4317202840",
    name: "World Fuel Services Corporation",
    note: "Repair gb laceration",
    amount: 80,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7596948634",
    name: "Pope Resources",
    note: "Percu endosc jejunostomy",
    amount: 52,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4435920026",
    name: "Vedanta  Limited",
    note: "Ins intra-ansm pres mntr",
    amount: 43,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7951269956",
    name: "TriMas Corporation",
    note: "Total body scan",
    amount: 84,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5278253878",
    name: "Fox Factory Holding Corp.",
    note: "Oth heart revascular",
    amount: 14,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "8726372002",
    name: "Northeast Bancorp",
    note: "Episiotomy",
    amount: 79,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0582577020",
    name: "Guidewire Software, Inc.",
    note: "Full-mouth x-ray",
    amount: 63,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5303555747",
    name: "QAD Inc.",
    note: "Small bowel fixation NEC",
    amount: 19,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6038508635",
    name: "Hertz Global Holdings, Inc",
    note: "Nasal lesion excis NOS",
    amount: 25,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6628977056",
    name: "Atlantic Power Corporation",
    note: "Transposit hand musc NEC",
    amount: 94,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1953979211",
    name: "Gladstone Investment Corporation",
    note: "Repair of cleft hand",
    amount: 67,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6052656913",
    name: "Jaguar Animal Health, Inc.",
    note: "Oth rep int cervical os",
    amount: 1,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5437190239",
    name: "CEVA, Inc.",
    note: "Stapedectomy NEC",
    amount: 40,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5076760507",
    name: "Nuveen AMT-Free Municipal Credit Income Fund",
    note: "Rev stapdec w incus repl",
    amount: 6,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9275023328",
    name: "Brasilagro Cia Brasileira De Propriedades Agricolas",
    note: "Contr cerebr arteriogram",
    amount: 15,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0039534855",
    name: "Avenue Income Credit Strategies Fund",
    note: "Removal oth vag pessary",
    amount: 90,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9488017848",
    name: "GP Strategies Corporation",
    note: "Ins bone void filler",
    amount: 41,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "8118489809",
    name: "Putnam Master Intermediate Income Trust",
    note: "Bronchial repair NEC",
    amount: 64,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7733058325",
    name: "Sun Bancorp, Inc.",
    note: "Kidney transplant NEC",
    amount: 100,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6848203017",
    name: "Vanguard Global ex-U.S. Real Estate ETF",
    note: "Ins spinal fusion device",
    amount: 69,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9907633658",
    name: "IDEX Corporation",
    note: "Angio oth non-coronary",
    amount: 14,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0309394279",
    name: "Community Health Systems, Inc.",
    note: "Sex transformat op NEC",
    amount: 46,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4913292943",
    name: "Selecta Biosciences, Inc.",
    note: "Prod subq tunnel no anas",
    amount: 25,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0869446274",
    name: "Calamos Global Total Return Fund",
    note: "Lid reconstr w graft NEC",
    amount: 71,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3630113222",
    name: "Bank of America Corporation",
    note: "Obstetric operation NEC",
    amount: 61,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7808176664",
    name: "First Trust",
    note: "Temp detach >1 xtroc mus",
    amount: 37,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4537446064",
    name: "CafePress Inc.",
    note: "Open red-int fix humerus",
    amount: 75,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6872732040",
    name: "Tekla Healthcare Investors",
    note: "Opn tricus valvuloplasty",
    amount: 12,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3903498556",
    name: "Teekay Offshore Partners L.P.",
    note: "Remov imp dev-tib/fibula",
    amount: 78,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5997496643",
    name: "Forestar Group Inc",
    note: "Open reduct-int fix toe",
    amount: 33,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9397271555",
    name: "Farmers & Merchants Bancorp, Inc.",
    note: "Arth/pros rem wo rep NEC",
    amount: 98,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "2384563769",
    name: "Intellipharmaceutics International Inc.",
    note: "Esophageal web incision",
    amount: 63,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5011714195",
    name: "Columbia Seligman Premium Technology Growth Fund, Inc",
    note: "Homograft to skin",
    amount: 33,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "2652620703",
    name: "Penumbra, Inc.",
    note: "Intralum urete adhesioly",
    amount: 37,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0562736883",
    name: "Legg Mason Emerging Markets Diversified Core ETF",
    note: "Other chest wall repair",
    amount: 96,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7213355058",
    name: "Calamos Global Total Return Fund",
    note: "Vulvar adhesiolysis",
    amount: 38,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7769678811",
    name: "Sally Beauty Holdings, Inc.",
    note: "Resistive exercise",
    amount: 93,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5264149925",
    name: "Wheeler Real Estate Investment Trust, Inc.",
    note: "Other destruc bronc les",
    amount: 50,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0598868569",
    name: "Patriot National Bancorp Inc.",
    note: "Other fusion of foot",
    amount: 58,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6104653057",
    name: "Lennox International, Inc.",
    note: "Pubiotomy to assist del",
    amount: 49,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1632535718",
    name: "Revlon, Inc.",
    note: "Periren/uret dx proc NEC",
    amount: 54,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6240219428",
    name: "MakeMyTrip Limited",
    note: "Closure of mouth fistula",
    amount: 79,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4279077932",
    name: "Everi Holdings Inc.",
    note: "Replace bladder stimulat",
    amount: 33,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4965703006",
    name: "PrivateBancorp, Inc.",
    note: "Intrathor lymphangiogram",
    amount: 89,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6525586453",
    name: "MagnaChip Semiconductor Corporation",
    note: "Arth/pros rem wo rep-hip",
    amount: 83,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6456753511",
    name: "Horizon Global Corporation",
    note: "Opn/oth part gastrectomy",
    amount: 48,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6156479627",
    name: "The Hain Celestial Group, Inc.",
    note: "Bilat ing hernia rep NOS",
    amount: 38,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3806119031",
    name: "CDW Corporation",
    note: "Ven cath renal dialysis",
    amount: 32,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5920662093",
    name: "Liberty Broadband Corporation",
    note: "Humerus sequestrectomy",
    amount: 11,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1303299283",
    name: "Kansas City Southern",
    note: "TRAM flap, pedicled",
    amount: 9,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9438430474",
    name: "China Life Insurance Company Limited",
    note: "Eyelid dx procedure NEC",
    amount: 70,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7287407639",
    name: "Goldman Sachs Group, Inc. (The)",
    note: "Remov intralum pharyn FB",
    amount: 29,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0983863938",
    name: "John Hancock Tax-Advantaged Global Shareholder Yield Fund",
    note: "Ileal conduitogram",
    amount: 29,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6194871377",
    name: "SunOpta, Inc.",
    note: "Hysterotomy to termin pg",
    amount: 1,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4303013544",
    name: "Countrywide Financial Corporation",
    note: "Separat unequl join twin",
    amount: 64,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3857487313",
    name: "United States Lime & Minerals, Inc.",
    note: "Achillotenotomy",
    amount: 93,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7713203621",
    name: "Orthofix International N.V.",
    note: "Labial frenotomy",
    amount: 83,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "5201368387",
    name: "Blackrock Capital and Income Strategies Fund Inc",
    note: "C-vasc scan/isotop funct",
    amount: 28,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6079461080",
    name: "Industrial Services of America, Inc.",
    note: "Rect/perirect dx op NEC",
    amount: 73,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1164257528",
    name: "Atlantic Power Corporation",
    note: "Repair of ovary NEC",
    amount: 93,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9406964554",
    name: "Forum Energy Technologies, Inc.",
    note: "Cl reduc disloc NOS",
    amount: 71,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "6454562107",
    name: "TOR Minerals International Inc",
    note: "Detach retina xenon coag",
    amount: 81,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "9620026934",
    name: "Spirit Airlines, Inc.",
    note: "Disarticulation of ankle",
    amount: 54,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1981528202",
    name: "Repros Therapeutics Inc.",
    note: "Sinus aspirat/lavage NOS",
    amount: 76,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1652947299",
    name: "MagneGas Corporation",
    note: "Ext ear diagnos proc NEC",
    amount: 92,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "7151217595",
    name: "New York & Company, Inc.",
    note: "Sympath nerve inject NEC",
    amount: 98,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "8758151389",
    name: "Vaalco Energy Inc",
    note: "Hip surface, cermc/cermc",
    amount: 32,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "1194965121",
    name: "Knowles Corporation",
    note: "Cell blk/pap-bili/pancre",
    amount: 39,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "0652390412",
    name: "Sharps Compliance Corp",
    note: "Polio vaccine administra",
    amount: 76,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "2409317170",
    name: "MFA Financial, Inc.",
    note: "Repair of mallet finger",
    amount: 53,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "4076098366",
    name: "Liberty Tax, Inc.",
    note: "Hand tend pulley reconst",
    amount: 18,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "3129188878",
    name: "Modern Media Acquisition Corp.",
    note: "Limb length measurement",
    amount: 31,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
  {
    id: "8400317092",
    name: "Principal Price Setters Index ETF",
    note: "Op bi dr/in ig hr-gr NEC",
    amount: 51,
    date: randomDate(),
    type: getRandomType(),
    balance: 100,
  },
];
export default data;
